title: Aditya Patra # your name (or website title) here
logo: "/images/9DS_5892 (1).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated with an MS in Mechanical Engineering, specializing in Robotics & Controls, from Carnegie Mellon University in Dec 2020. 
  <br><br>
  My core competencies lie in Applied Deep Learning for perception and data generation, Computer Vision, Robotics and Controls System. 
  <br><br>
  <a href="https://www.linkedin.com/in/patra-aditya/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
